name: 'Github MergeTag'
description: 'Tags merge commits with branch name'
author: 'Planet'
inputs:
  branch:
    description: 'The head branch of the pull request'
    default: ${{ github.head_ref }}
runs:
  using: 'node12'
  main: 'dist/index.js'
